name: Import and Merge DNS Blocklists

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 * * * *"    #runs every hour
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Execute py script
        run: python import-merge-blocklist.py

      - name: Upload blocklist to GitHub Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dns-blocklist-latest
          name: Latest DNS Blocklist
          body: Automatically generated DNS blocklist.
          files: merged-dns-blocklist.txt
          overwrite_files: true
